// Engine adapter interface and implementations for Claude Code CLI and OpenAI Codex CLI.
// Each adapter encapsulates the CLI-specific details: argument construction, MCP config
// format, and JSONL event parsing — so the bridge layer remains engine-agnostic.

import { resolve } from "node:path";
import { writeFileSync, unlinkSync } from "node:fs";
import { tmpdir } from "node:os";

// ---------------------------------------------------------------------------
// Shared types
// ---------------------------------------------------------------------------

export interface McpServerDef {
  command: string;
  args: string[];
  env?: Record<string, string>;
}

export type ParsedEvent =
  | { kind: "text"; text: string; sessionId?: string }
  | { kind: "tool_use"; toolName: string; sessionId?: string }
  | { kind: "result"; sessionId?: string; result?: string };

export interface BuildArgsParams {
  prompt: string;
  model: string;
  systemPrompt: string;
  mcpConfigPath: string;
  conversationId?: string;
  imagePaths?: string[];
}

export interface EngineAdapter {
  readonly name: string;

  /** Write engine-specific MCP config. Called once at startup. Returns path and cleanup fn. */
  setupMcpConfig(mcpServers: Record<string, McpServerDef>): {
    configPath: string;
    cleanup: () => void;
  };

  /** Build CLI command and arguments for a single invocation. */
  buildArgs(params: BuildArgsParams): { command: string; args: string[] };

  /** Parse a single JSONL line (already JSON.parsed) into a normalized event. Null = skip. */
  parseEvent(json: unknown): ParsedEvent | null;
}

// ---------------------------------------------------------------------------
// Claude Code CLI Adapter
// ---------------------------------------------------------------------------

export class ClaudeAdapter implements EngineAdapter {
  readonly name = "Claude";

  setupMcpConfig(mcpServers: Record<string, McpServerDef>) {
    const configPath = resolve(tmpdir(), `minister-mcp-${process.pid}.json`);
    writeFileSync(configPath, JSON.stringify({ mcpServers }, null, 2), { mode: 0o600 });

    const cleanup = () => {
      try { unlinkSync(configPath); } catch { /* already gone */ }
    };
    return { configPath, cleanup };
  }

  buildArgs(params: BuildArgsParams) {
    const args = [
      "--print",
      "--permission-mode", "auto",
      "--verbose",
      "--output-format", "stream-json",
      "--model", params.model,
      "--system-prompt", params.systemPrompt,
      "--mcp-config", params.mcpConfigPath,
    ];

    if (params.conversationId) {
      args.push("--resume", params.conversationId);
    }

    // "--" separates options from positional args
    args.push("--", params.prompt);

    return { command: "claude", args };
  }

  parseEvent(json: unknown): ParsedEvent | null {
    const event = json as Record<string, unknown>;

    if (event.type === "assistant") {
      const message = event.message as Record<string, unknown> | undefined;
      const contentBlocks = message?.content as Array<Record<string, unknown>> | undefined;
      if (!Array.isArray(contentBlocks)) return null;

      // Accumulate text and tool_use from a single assistant event.
      // Return only the first meaningful item; the bridge handles multiple events per line.
      for (const block of contentBlocks) {
        if (block.type === "text" && block.text) {
          return {
            kind: "text",
            text: block.text as string,
            sessionId: event.session_id as string | undefined,
          };
        }
        if (block.type === "tool_use") {
          return {
            kind: "tool_use",
            toolName: (block.name as string) || "unknown",
            sessionId: event.session_id as string | undefined,
          };
        }
      }

      return null;
    }

    if (event.type === "result") {
      return {
        kind: "result",
        sessionId: (event.session_id as string) || undefined,
        result: (event.result as string) || undefined,
      };
    }

    return null;
  }
}

// ---------------------------------------------------------------------------
// OpenAI Codex CLI Adapter
// ---------------------------------------------------------------------------

export class CodexAdapter implements EngineAdapter {
  readonly name = "Codex";

  setupMcpConfig(_mcpServers: Record<string, McpServerDef>) {
    // Codex reads ~/.codex/config.toml (global) which is generated by
    // scripts/generate-codex-config.ts in the Docker entrypoint. No file
    // writing here — avoids overwriting the user's personal config locally.
    return { configPath: "", cleanup: () => {} };
  }

  buildArgs(params: BuildArgsParams) {
    // Model/provider/MCP config lives in ~/.codex/config.toml (written at startup).
    // System prompt is delivered via AGENTS.override.md in the worktree.
    const args: string[] = ["exec"];

    if (params.conversationId) {
      args.push("resume", params.conversationId);
    }

    args.push("--json", "--full-auto", "--skip-git-repo-check");

    for (const p of params.imagePaths ?? []) {
      args.push("-i", p);
    }

    args.push(params.prompt);
    return { command: "codex", args };
  }

  parseEvent(json: unknown): ParsedEvent | null {
    const event = json as Record<string, unknown>;
    const type = event.type as string;

    // Thread started — extract session/thread ID
    if (type === "thread.started") {
      const threadId = (event.thread_id ?? event.id ?? event.session_id) as string | undefined;
      if (threadId) {
        return { kind: "result", sessionId: threadId };
      }
      return null;
    }

    // Item events — assistant messages and tool calls
    if (type === "item.updated" || type === "item.completed" || type === "item.started") {
      const item = event.item as Record<string, unknown> | undefined;
      if (!item) return null;

      const itemType = item.type as string;

      // Assistant / agent text output
      if (itemType === "assistant_message" || itemType === "agent_message") {
        // agent_message: text is directly on item.text
        if (item.text) {
          return { kind: "text", text: item.text as string };
        }
        // assistant_message: text is in item.content[].text
        const contentBlocks = item.content as Array<Record<string, unknown>> | undefined;
        if (Array.isArray(contentBlocks)) {
          for (const block of contentBlocks) {
            if ((block.type === "output_text" || block.type === "text") && block.text) {
              return { kind: "text", text: block.text as string };
            }
          }
        }
        return null;
      }

      // MCP tool calls
      if (itemType === "mcp_tool_call" && type === "item.completed") {
        const toolName = (item.name as string) || "unknown";
        return { kind: "tool_use", toolName };
      }

      // Command execution (shell tool)
      if (itemType === "command_execution" && type === "item.completed") {
        return { kind: "tool_use", toolName: "Bash" };
      }

      // File changes
      if (itemType === "file_change" && type === "item.completed") {
        return { kind: "tool_use", toolName: "Edit" };
      }

      return null;
    }

    // Turn completed — final result
    if (type === "turn.completed") {
      const lastText = (event.last_text ?? event.result) as string | undefined;
      return { kind: "result", result: lastText || undefined };
    }

    // Error events — surface as text so the user sees what went wrong
    if (type === "error") {
      const msg = (event.message as string) || "unknown error";
      return { kind: "text", text: `[Codex Error] ${msg}` };
    }

    if (type === "turn.failed") {
      const err = event.error as Record<string, unknown> | undefined;
      const msg = (err?.message as string) || "turn failed";
      return { kind: "text", text: `[Codex Error] ${msg}` };
    }

    return null;
  }
}
